// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Argonne.Common.ArgonneService.Models;
using Newtonsoft.Json.Linq;

namespace Argonne.Common.ArgonneService.Models
{
    public static partial class AdInCampaignDtoCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<AdInCampaignDto> DeserializeJson(JToken inputObject)
        {
            IList<AdInCampaignDto> deserializedObject = new List<AdInCampaignDto>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                AdInCampaignDto adInCampaignDto = new AdInCampaignDto();
                adInCampaignDto.DeserializeJson(iListValue);
                deserializedObject.Add(adInCampaignDto);
            }
            return deserializedObject;
        }
    }
}
