// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Argonne.Common.ArgonneService.Models;
using Newtonsoft.Json.Linq;

namespace Argonne.Common.ArgonneService.Models
{
    public partial class AdsForCampaigns
    {
        private Ads _ad;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public Ads AD
        {
            get { return this._ad; }
            set { this._ad = value; }
        }
        
        private string _adId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string AdId
        {
            get { return this._adId; }
            set { this._adId = value; }
        }
        
        private Campaigns _campaign;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public Campaigns Campaign
        {
            get { return this._campaign; }
            set { this._campaign = value; }
        }
        
        private string _campaignId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string CampaignId
        {
            get { return this._campaignId; }
            set { this._campaignId = value; }
        }
        
        private int? _duration;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Duration
        {
            get { return this._duration; }
            set { this._duration = value; }
        }
        
        private int? _firstImpression;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? FirstImpression
        {
            get { return this._firstImpression; }
            set { this._firstImpression = value; }
        }
        
        private int? _impressionInterval;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? ImpressionInterval
        {
            get { return this._impressionInterval; }
            set { this._impressionInterval = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the AdsForCampaigns class.
        /// </summary>
        public AdsForCampaigns()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken adValue = inputObject["ad"];
                if (adValue != null && adValue.Type != JTokenType.Null)
                {
                    Ads ads = new Ads();
                    ads.DeserializeJson(adValue);
                    this.AD = ads;
                }
                JToken adIdValue = inputObject["adId"];
                if (adIdValue != null && adIdValue.Type != JTokenType.Null)
                {
                    this.AdId = ((string)adIdValue);
                }
                JToken campaignValue = inputObject["campaign"];
                if (campaignValue != null && campaignValue.Type != JTokenType.Null)
                {
                    Campaigns campaigns = new Campaigns();
                    campaigns.DeserializeJson(campaignValue);
                    this.Campaign = campaigns;
                }
                JToken campaignIdValue = inputObject["campaignId"];
                if (campaignIdValue != null && campaignIdValue.Type != JTokenType.Null)
                {
                    this.CampaignId = ((string)campaignIdValue);
                }
                JToken durationValue = inputObject["duration"];
                if (durationValue != null && durationValue.Type != JTokenType.Null)
                {
                    this.Duration = ((int)durationValue);
                }
                JToken firstImpressionValue = inputObject["firstImpression"];
                if (firstImpressionValue != null && firstImpressionValue.Type != JTokenType.Null)
                {
                    this.FirstImpression = ((int)firstImpressionValue);
                }
                JToken impressionIntervalValue = inputObject["impressionInterval"];
                if (impressionIntervalValue != null && impressionIntervalValue.Type != JTokenType.Null)
                {
                    this.ImpressionInterval = ((int)impressionIntervalValue);
                }
            }
        }
    }
}
