// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Argonne.Common.ArgonneService.Models
{
    public partial class CampaignDto
    {
        private string _campaignId;
        
        /// <summary>
        /// Optional. Globally unique identifier for campaign assigned by
        /// Argonne system
        /// </summary>
        public string CampaignId
        {
            get { return this._campaignId; }
            set { this._campaignId = value; }
        }
        
        private string _campaignName;
        
        /// <summary>
        /// Required. Name of Campaign
        /// </summary>
        public string CampaignName
        {
            get { return this._campaignName; }
            set { this._campaignName = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the CampaignDto class.
        /// </summary>
        public CampaignDto()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the CampaignDto class with required
        /// arguments.
        /// </summary>
        public CampaignDto(string campaignName)
            : this()
        {
            if (campaignName == null)
            {
                throw new ArgumentNullException("campaignName");
            }
            this.CampaignName = campaignName;
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken campaignIdValue = inputObject["campaignId"];
                if (campaignIdValue != null && campaignIdValue.Type != JTokenType.Null)
                {
                    this.CampaignId = ((string)campaignIdValue);
                }
                JToken campaignNameValue = inputObject["campaignName"];
                if (campaignNameValue != null && campaignNameValue.Type != JTokenType.Null)
                {
                    this.CampaignName = ((string)campaignNameValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type CampaignDto
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.CampaignName == null)
            {
                throw new ArgumentNullException("CampaignName");
            }
            if (this.CampaignId != null)
            {
                outputObject["campaignId"] = this.CampaignId;
            }
            if (this.CampaignName != null)
            {
                outputObject["campaignName"] = this.CampaignName;
            }
            return outputObject;
        }
    }
}
