// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Argonne.Common.ArgonneService.Models;
using Newtonsoft.Json.Linq;

namespace Argonne.Common.ArgonneService.Models
{
    public static partial class CampaignDtoCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<CampaignDto> DeserializeJson(JToken inputObject)
        {
            IList<CampaignDto> deserializedObject = new List<CampaignDto>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                CampaignDto campaignDto = new CampaignDto();
                campaignDto.DeserializeJson(iListValue);
                deserializedObject.Add(campaignDto);
            }
            return deserializedObject;
        }
    }
}
