using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using ArgonneWebApi.Models.Datastore;
using ArgonneWebApi.Models.Dto;
using ArgonneWebApi.Models.Validation;
using ArgonneWebApi.Repositories;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;

namespace ArgonneWebApi.Controllers
{
    /// <summary>
    /// Administrator API for Campaigns
    /// </summary>
    //[Route("api/admin/[controller]")]
    [Produces("application/json")]
    public class CampaignController : Controller
    {
        private IEntityRepository<Campaigns> repository;
        private IEntityRepository<AdsForCampaigns> adForCampaignRepository;
        private IMapper mapper;

        /// <summary>
        /// Constructor
        /// </summary>
        /// <param name="repo"></param>
        /// <param name="entityMapper"></param>
        public CampaignController(IEntityRepository<Campaigns> repo, IEntityRepository<AdsForCampaigns> adCampRepo, IMapper entityMapper)
        {
            repository = repo;
            mapper = entityMapper;
            adForCampaignRepository = adCampRepo;
        }

        /// <summary>
        /// Get all campaigns
        /// </summary>
        /// <response code="200">Success</response>
        [Route("api/admin/[controller]")]
        [HttpGet]
        [ProducesResponseType(typeof(IEnumerable<CampaignDto>), 200)]
        public async Task<IActionResult> GetAll()
        {
            return new OkObjectResult(mapper.Map<IEnumerable<Campaigns>, IEnumerable<CampaignDto>>(await repository.GetAll().ConfigureAwait(false)));
        }

        /// <summary>
        /// Get a campaign by id
        /// </summary>
        /// <param name="id">unique identifier for a campaign</param>
        /// <remarks>
        /// Id must be a valid GUID
        /// </remarks>
        /// <response code="200">Success</response>
        /// <response code="404">Not Found</response>
        /// <response code="400">Invalid Id</response>
        //[HttpGet("{id}", Name = "GetCampaign")]
        [HttpGet]
        [Route("api/admin/[controller]/{id}")]
        [ProducesResponseType(typeof(CampaignDto), 200)]
        public async Task<IActionResult> Get(string id)
        {
            if (string.IsNullOrEmpty(id))
                return BadRequest();

            Guid idGuid;
            if(!Guid.TryParse(id, out idGuid))
            {
                return BadRequest();
            }

            var result = mapper.Map<Campaigns, CampaignDto>(
                await repository.GetSingle(item => item.CampaignId == idGuid).ConfigureAwait(false));

            if (null == result)
                return NotFound();

            return new OkObjectResult(result);
        }


        /// <summary>
        /// Create a new Campaign
        /// </summary>
        /// <remarks>
        /// Id field does not need to be supplied, it is ignored. The unique identifier for the Campaign will be generated by the system.
        /// </remarks>
        /// <response code="201">Created</response>
        /// <response code="400">Invalid Model</response>
        [HttpPost]
        [Route("api/admin/[controller]")]
        [ProducesResponseType(typeof(CampaignDto), 201)]
        public async Task<IActionResult> Create([FromBody]CampaignDto item)
        {
            if (item == null)
            {
                return BadRequest();
            }

            var validator = new CampaignValidator();
            var validationResults = validator.Validate(item);
            if(!validationResults.IsValid)
            {
                return BadRequest(validationResults.Errors);
            }

            item.CampaignId = Guid.NewGuid();

            //TODO: Business Rule validations?

            await repository.Add(mapper.Map<CampaignDto, Campaigns>(item)).ConfigureAwait(false);

            return CreatedAtRoute("GetCampaign", new { Controller = "Campaign", id = item.CampaignId }, item);
        }

        /// <summary>
        /// Modify an existing Campaign
        /// </summary>
        /// <param name="updatedRecord">modified Campaign model</param>
        /// <remarks>
        /// Campaign Id must be a valid GUID
        /// </remarks>
        /// <response code="200">Success</response>
        /// <response code="404">Not Found</response>
        /// <response code="400">Invalid Id or Model</response>
        [HttpPut]
        [Route("api/admin/[controller]")]
        public async Task<IActionResult> Update([FromBody]CampaignDto updatedRecord)
        {
            if (updatedRecord == null)
            {
                return BadRequest();
            }

            var validator = new CampaignValidator(true);
            var validationResults = validator.Validate(updatedRecord);
            if (!validationResults.IsValid)
            {
                return BadRequest(validationResults.Errors);
            }

            var existingRecord = await repository.GetSingle(item => item.CampaignId == updatedRecord.CampaignId).ConfigureAwait(false);
            if (null == existingRecord)
                return NotFound();

            mapper.Map<CampaignDto, Campaigns>(updatedRecord, existingRecord);
            await repository.Update(existingRecord).ConfigureAwait(false);
            return Ok();
        }

        /// <summary>
        /// Delete an existing Campaign
        /// </summary>
        /// <param name="id">unique identifier for a Campaign</param>
        /// <remarks>
        /// Id must be a valid GUID
        /// </remarks>
        /// <response code="200">Success</response>
        /// <response code="400">Invalid Id</response>
        [HttpDelete]
        [Route("api/admin/[controller]/{id}")]
        public async Task<IActionResult> Delete(string id)
        {
            if (string.IsNullOrEmpty(id))
                return BadRequest();

            Guid idGuid;
            if (!Guid.TryParse(id, out idGuid))
            {
                return BadRequest();
            }

            await repository.DeleteWhere(item => item.CampaignId == idGuid).ConfigureAwait(false);

            return Ok();
        }

        #region relationships
        /// <summary>
        /// Get all ads for a campaign
        /// </summary>
        /// <param name="id">unique identifier for a campaign</param>
        /// <remarks>
        /// Id must be a valid GUID
        /// </remarks>
        /// <response code="200">Success</response>
        /// <response code="404">Not Found</response>
        /// <response code="400">Invalid Id</response>
        [Route("api/admin/[controller]/{id}/Ads")]
        //[HttpGet("{id}", Name = "GetAds")]
        [HttpGet]
        [ProducesResponseType(typeof(IEnumerable<AdInCampaignDto>), 200)]
        public async Task<IActionResult> GetAds(string id)
        {
            if (string.IsNullOrEmpty(id))
                return BadRequest();

            Guid idGuid;
            if (!Guid.TryParse(id, out idGuid))
            {
                return BadRequest();
            }


            var relations = await adForCampaignRepository.FindBy(item => item.CampaignId == idGuid);
            if (null == relations)
                return NotFound();
            var result = mapper.Map<IEnumerable<AdsForCampaigns>, IEnumerable<AdInCampaignDto>>(relations);
            return new OkObjectResult(result);
        }

        /// <summary>
        /// Add an Ad to a Campaign
        /// </summary>
        /// <remarks>
        /// Id field does not need to be supplied, it is ignored. The unique identifier for the Campaign will be generated by the system.
        /// </remarks>
        /// <response code="201">Created</response>
        /// <response code="400">Invalid Model</response>
        [Route("api/admin/[controller]/{id}/Ads")]
        [HttpPost]
        [ProducesResponseType(typeof(AdInCampaignDto), 201)]
        public async Task<IActionResult> AddAdToCampaign([FromBody]AdInCampaignDto item)
        {
            if (item == null)
            {
                return BadRequest();
            }

            var validator = new AdInCampaignValidator();
            var validationResults = validator.Validate(item);
            if (!validationResults.IsValid)
            {
                return BadRequest(validationResults.Errors);
            }

            await adForCampaignRepository.Add(mapper.Map<AdInCampaignDto, AdsForCampaigns>(item)).ConfigureAwait(false);

            return CreatedAtRoute("{Id}/Ads", new { Controller = "Campaign", id = item.CampaignId }, item);
        }
        #endregion
    }
}
