// Generated by typings
// Source: scripts/TypeLite.Net4.d.ts
declare module Argonne.Services.ArgonneService.Models {
	interface AdDto {
		AdId: string;
		AdName: string;
		Url: string;
	}
	interface CampaignDto {
		CampaignId: string;
		CampaignName: string;
	}
	interface DeviceDto {
		ActiveFrom: Date;
		ActiveTo: Date;
		Address: string;
		Address2: string;
		Address3: string;
		CampaignId: string;
		City: string;
		DeviceId: string;
		DeviceName: string;
		PostalCode: string;
		PrimaryKey: string;
		StateProvince: string;
		Timezone: string;
	}
	interface FaceForImpressionDto {
		Age: number;
		FaceId: string;
		Gender: string;
		ImpressionId: number;
		ScoreAnger: number;
		ScoreContempt: number;
		ScoreDisgust: number;
		ScoreFear: number;
		ScoreHappiness: number;
		ScoreNeutral: number;
		ScoreSadness: number;
		ScoreSurprise: number;
		Sequence: number;
	}
	interface ImpressionDto {
		CampaignId: string;
		DeviceId: string;
		DeviceTimestamp: Date;
		DisplayedAdId: string;
		Faces: Argonne.Services.ArgonneService.Models.FaceForImpressionDto[];
		ImpressionId: number;
		InsertTimestamp: Date;
		MessageId: string;
	}
}
declare module Models {
	interface List {
		Count: number;
		CountEnded: number;
		Id: number;
		Name: string;
		Tasks: Models.Task[];
	}
	interface Task {
		Ended: boolean;
		Id: number;
		ListId: number;
		Name: string;
	}
}
