// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using ArgonneService.Models;
using Newtonsoft.Json.Linq;

namespace ArgonneService.Models
{
    public static partial class AdAggregateDataCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<AdAggregateData> DeserializeJson(JToken inputObject)
        {
            IList<AdAggregateData> deserializedObject = new List<AdAggregateData>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                AdAggregateData adAggregateData = new AdAggregateData();
                adAggregateData.DeserializeJson(iListValue);
                deserializedObject.Add(adAggregateData);
            }
            return deserializedObject;
        }
    }
}
