// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace ArgonneService.Models
{
    public partial class AdAggregateData
    {
        private string _adId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string AdId
        {
            get { return this._adId; }
            set { this._adId = value; }
        }
        
        private int? _ageBracket1;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? AgeBracket1
        {
            get { return this._ageBracket1; }
            set { this._ageBracket1 = value; }
        }
        
        private int? _ageBracket2;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? AgeBracket2
        {
            get { return this._ageBracket2; }
            set { this._ageBracket2 = value; }
        }
        
        private int? _ageBracket3;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? AgeBracket3
        {
            get { return this._ageBracket3; }
            set { this._ageBracket3 = value; }
        }
        
        private int? _ageBracket4;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? AgeBracket4
        {
            get { return this._ageBracket4; }
            set { this._ageBracket4 = value; }
        }
        
        private int? _ageBracket5;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? AgeBracket5
        {
            get { return this._ageBracket5; }
            set { this._ageBracket5 = value; }
        }
        
        private int? _ageBracket6;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? AgeBracket6
        {
            get { return this._ageBracket6; }
            set { this._ageBracket6 = value; }
        }
        
        private int? _females;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Females
        {
            get { return this._females; }
            set { this._females = value; }
        }
        
        private int? _males;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Males
        {
            get { return this._males; }
            set { this._males = value; }
        }
        
        private int? _totalFaces;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? TotalFaces
        {
            get { return this._totalFaces; }
            set { this._totalFaces = value; }
        }
        
        private int? _uniqueFaces;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? UniqueFaces
        {
            get { return this._uniqueFaces; }
            set { this._uniqueFaces = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the AdAggregateData class.
        /// </summary>
        public AdAggregateData()
        {
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken adIdValue = inputObject["adId"];
                if (adIdValue != null && adIdValue.Type != JTokenType.Null)
                {
                    this.AdId = ((string)adIdValue);
                }
                JToken ageBracket1Value = inputObject["ageBracket1"];
                if (ageBracket1Value != null && ageBracket1Value.Type != JTokenType.Null)
                {
                    this.AgeBracket1 = ((int)ageBracket1Value);
                }
                JToken ageBracket2Value = inputObject["ageBracket2"];
                if (ageBracket2Value != null && ageBracket2Value.Type != JTokenType.Null)
                {
                    this.AgeBracket2 = ((int)ageBracket2Value);
                }
                JToken ageBracket3Value = inputObject["ageBracket3"];
                if (ageBracket3Value != null && ageBracket3Value.Type != JTokenType.Null)
                {
                    this.AgeBracket3 = ((int)ageBracket3Value);
                }
                JToken ageBracket4Value = inputObject["ageBracket4"];
                if (ageBracket4Value != null && ageBracket4Value.Type != JTokenType.Null)
                {
                    this.AgeBracket4 = ((int)ageBracket4Value);
                }
                JToken ageBracket5Value = inputObject["ageBracket5"];
                if (ageBracket5Value != null && ageBracket5Value.Type != JTokenType.Null)
                {
                    this.AgeBracket5 = ((int)ageBracket5Value);
                }
                JToken ageBracket6Value = inputObject["ageBracket6"];
                if (ageBracket6Value != null && ageBracket6Value.Type != JTokenType.Null)
                {
                    this.AgeBracket6 = ((int)ageBracket6Value);
                }
                JToken femalesValue = inputObject["females"];
                if (femalesValue != null && femalesValue.Type != JTokenType.Null)
                {
                    this.Females = ((int)femalesValue);
                }
                JToken malesValue = inputObject["males"];
                if (malesValue != null && malesValue.Type != JTokenType.Null)
                {
                    this.Males = ((int)malesValue);
                }
                JToken totalFacesValue = inputObject["totalFaces"];
                if (totalFacesValue != null && totalFacesValue.Type != JTokenType.Null)
                {
                    this.TotalFaces = ((int)totalFacesValue);
                }
                JToken uniqueFacesValue = inputObject["uniqueFaces"];
                if (uniqueFacesValue != null && uniqueFacesValue.Type != JTokenType.Null)
                {
                    this.UniqueFaces = ((int)uniqueFacesValue);
                }
            }
        }
    }
}
