// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using ArgonneService.Models;
using Newtonsoft.Json.Linq;

namespace ArgonneService.Models
{
    public static partial class AdDtoCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<AdDto> DeserializeJson(JToken inputObject)
        {
            IList<AdDto> deserializedObject = new List<AdDto>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                AdDto adDto = new AdDto();
                adDto.DeserializeJson(iListValue);
                deserializedObject.Add(adDto);
            }
            return deserializedObject;
        }
    }
}
