// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;
using TypeLite;

namespace Argonne.Services.ArgonneService.Models
{
    [TsClass]
    public partial class AdDto
    {
        private string _adId;
        
        /// <summary>
        /// Optional. Globally unique identifier assigned by the Argonne system
        /// </summary>
        public string AdId
        {
            get { return this._adId; }
            set { this._adId = value; }
        }
        
        private string _adName;
        
        /// <summary>
        /// Required. User friendly name for an ad
        /// </summary>
        public string AdName
        {
            get { return this._adName; }
            set { this._adName = value; }
        }
        
        private string _url;
        
        /// <summary>
        /// Required. Url for ad media
        /// </summary>
        public string Url
        {
            get { return this._url; }
            set { this._url = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the AdDto class.
        /// </summary>
        public AdDto()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the AdDto class with required
        /// arguments.
        /// </summary>
        public AdDto(string adName, string url)
            : this()
        {
            if (adName == null)
            {
                throw new ArgumentNullException("adName");
            }
            if (url == null)
            {
                throw new ArgumentNullException("url");
            }
            this.AdName = adName;
            this.Url = url;
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken adIdValue = inputObject["adId"];
                if (adIdValue != null && adIdValue.Type != JTokenType.Null)
                {
                    this.AdId = ((string)adIdValue);
                }
                JToken adNameValue = inputObject["adName"];
                if (adNameValue != null && adNameValue.Type != JTokenType.Null)
                {
                    this.AdName = ((string)adNameValue);
                }
                JToken urlValue = inputObject["url"];
                if (urlValue != null && urlValue.Type != JTokenType.Null)
                {
                    this.Url = ((string)urlValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type AdDto
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.AdName == null)
            {
                throw new ArgumentNullException("AdName");
            }
            if (this.Url == null)
            {
                throw new ArgumentNullException("Url");
            }
            if (this.AdId != null)
            {
                outputObject["adId"] = this.AdId;
            }
            if (this.AdName != null)
            {
                outputObject["adName"] = this.AdName;
            }
            if (this.Url != null)
            {
                outputObject["url"] = this.Url;
            }
            return outputObject;
        }
    }
}
