// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;

namespace Argonne.Services.ArgonneService.Models
{
    public partial class AdInCampaignDto
    {
        private string _adId;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string AdId
        {
            get { return this._adId; }
            set { this._adId = value; }
        }
        
        private string _campaignId;
        
        /// <summary>
        /// Required.
        /// </summary>
        public string CampaignId
        {
            get { return this._campaignId; }
            set { this._campaignId = value; }
        }
        
        private int? _duration;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? Duration
        {
            get { return this._duration; }
            set { this._duration = value; }
        }
        
        private int? _firstImpression;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? FirstImpression
        {
            get { return this._firstImpression; }
            set { this._firstImpression = value; }
        }
        
        private int? _impressionInterval;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public int? ImpressionInterval
        {
            get { return this._impressionInterval; }
            set { this._impressionInterval = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the AdInCampaignDto class.
        /// </summary>
        public AdInCampaignDto()
        {
        }
        
        /// <summary>
        /// Initializes a new instance of the AdInCampaignDto class with
        /// required arguments.
        /// </summary>
        public AdInCampaignDto(string campaignId, string adId)
            : this()
        {
            if (campaignId == null)
            {
                throw new ArgumentNullException("campaignId");
            }
            if (adId == null)
            {
                throw new ArgumentNullException("adId");
            }
            this.CampaignId = campaignId;
            this.AdId = adId;
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken adIdValue = inputObject["adId"];
                if (adIdValue != null && adIdValue.Type != JTokenType.Null)
                {
                    this.AdId = ((string)adIdValue);
                }
                JToken campaignIdValue = inputObject["campaignId"];
                if (campaignIdValue != null && campaignIdValue.Type != JTokenType.Null)
                {
                    this.CampaignId = ((string)campaignIdValue);
                }
                JToken durationValue = inputObject["duration"];
                if (durationValue != null && durationValue.Type != JTokenType.Null)
                {
                    this.Duration = ((int)durationValue);
                }
                JToken firstImpressionValue = inputObject["firstImpression"];
                if (firstImpressionValue != null && firstImpressionValue.Type != JTokenType.Null)
                {
                    this.FirstImpression = ((int)firstImpressionValue);
                }
                JToken impressionIntervalValue = inputObject["impressionInterval"];
                if (impressionIntervalValue != null && impressionIntervalValue.Type != JTokenType.Null)
                {
                    this.ImpressionInterval = ((int)impressionIntervalValue);
                }
            }
        }
        
        /// <summary>
        /// Serialize the object
        /// </summary>
        /// <returns>
        /// Returns the json model for the type AdInCampaignDto
        /// </returns>
        public virtual JToken SerializeJson(JToken outputObject)
        {
            if (outputObject == null)
            {
                outputObject = new JObject();
            }
            if (this.AdId == null)
            {
                throw new ArgumentNullException("AdId");
            }
            if (this.CampaignId == null)
            {
                throw new ArgumentNullException("CampaignId");
            }
            if (this.AdId != null)
            {
                outputObject["adId"] = this.AdId;
            }
            if (this.CampaignId != null)
            {
                outputObject["campaignId"] = this.CampaignId;
            }
            if (this.Duration != null)
            {
                outputObject["duration"] = this.Duration.Value;
            }
            if (this.FirstImpression != null)
            {
                outputObject["firstImpression"] = this.FirstImpression.Value;
            }
            if (this.ImpressionInterval != null)
            {
                outputObject["impressionInterval"] = this.ImpressionInterval.Value;
            }
            return outputObject;
        }
    }
}
