// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Argonne.Services.ArgonneService.Models;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;

namespace Argonne.Services.ArgonneService.Models
{
    public partial class Ads
    {
        private string _adId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string AdId
        {
            get { return this._adId; }
            set { this._adId = value; }
        }
        
        private string _adName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string AdName
        {
            get { return this._adName; }
            set { this._adName = value; }
        }
        
        private IList<AdsForCampaigns> _adsForCampaigns;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<AdsForCampaigns> AdsForCampaigns
        {
            get { return this._adsForCampaigns; }
            set { this._adsForCampaigns = value; }
        }
        
        private IList<Impressions> _impressions;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<Impressions> Impressions
        {
            get { return this._impressions; }
            set { this._impressions = value; }
        }
        
        private string _url;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Url
        {
            get { return this._url; }
            set { this._url = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Ads class.
        /// </summary>
        public Ads()
        {
            this.AdsForCampaigns = new LazyList<AdsForCampaigns>();
            this.Impressions = new LazyList<Impressions>();
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken adIdValue = inputObject["adId"];
                if (adIdValue != null && adIdValue.Type != JTokenType.Null)
                {
                    this.AdId = ((string)adIdValue);
                }
                JToken adNameValue = inputObject["adName"];
                if (adNameValue != null && adNameValue.Type != JTokenType.Null)
                {
                    this.AdName = ((string)adNameValue);
                }
                JToken adsForCampaignsSequence = ((JToken)inputObject["adsForCampaigns"]);
                if (adsForCampaignsSequence != null && adsForCampaignsSequence.Type != JTokenType.Null)
                {
                    foreach (JToken adsForCampaignsValue in ((JArray)adsForCampaignsSequence))
                    {
                        AdsForCampaigns adsForCampaigns = new AdsForCampaigns();
                        adsForCampaigns.DeserializeJson(adsForCampaignsValue);
                        this.AdsForCampaigns.Add(adsForCampaigns);
                    }
                }
                JToken impressionsSequence = ((JToken)inputObject["impressions"]);
                if (impressionsSequence != null && impressionsSequence.Type != JTokenType.Null)
                {
                    foreach (JToken impressionsValue in ((JArray)impressionsSequence))
                    {
                        Impressions impressions = new Impressions();
                        impressions.DeserializeJson(impressionsValue);
                        this.Impressions.Add(impressions);
                    }
                }
                JToken urlValue = inputObject["url"];
                if (urlValue != null && urlValue.Type != JTokenType.Null)
                {
                    this.Url = ((string)urlValue);
                }
            }
        }
    }
}
