// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Argonne.Services.ArgonneService.Models;
using Microsoft.Rest;
using Newtonsoft.Json.Linq;

namespace Argonne.Services.ArgonneService.Models
{
    public partial class Devices
    {
        private DateTimeOffset? _activeFrom;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? ActiveFrom
        {
            get { return this._activeFrom; }
            set { this._activeFrom = value; }
        }
        
        private DateTimeOffset? _activeTo;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public DateTimeOffset? ActiveTo
        {
            get { return this._activeTo; }
            set { this._activeTo = value; }
        }
        
        private string _address;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Address
        {
            get { return this._address; }
            set { this._address = value; }
        }
        
        private string _address2;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Address2
        {
            get { return this._address2; }
            set { this._address2 = value; }
        }
        
        private string _address3;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Address3
        {
            get { return this._address3; }
            set { this._address3 = value; }
        }
        
        private string _assignedCampaignId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string AssignedCampaignId
        {
            get { return this._assignedCampaignId; }
            set { this._assignedCampaignId = value; }
        }
        
        private BiasesForDevices _biasesForDevices;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public BiasesForDevices BiasesForDevices
        {
            get { return this._biasesForDevices; }
            set { this._biasesForDevices = value; }
        }
        
        private string _city;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string City
        {
            get { return this._city; }
            set { this._city = value; }
        }
        
        private Campaigns _currentCampaign;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public Campaigns CurrentCampaign
        {
            get { return this._currentCampaign; }
            set { this._currentCampaign = value; }
        }
        
        private string _deviceId;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string DeviceId
        {
            get { return this._deviceId; }
            set { this._deviceId = value; }
        }
        
        private string _deviceName;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string DeviceName
        {
            get { return this._deviceName; }
            set { this._deviceName = value; }
        }
        
        private IList<Impressions> _impressions;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public IList<Impressions> Impressions
        {
            get { return this._impressions; }
            set { this._impressions = value; }
        }
        
        private string _postalCode;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string PostalCode
        {
            get { return this._postalCode; }
            set { this._postalCode = value; }
        }
        
        private string _primaryKey;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string PrimaryKey
        {
            get { return this._primaryKey; }
            set { this._primaryKey = value; }
        }
        
        private string _stateProvince;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string StateProvince
        {
            get { return this._stateProvince; }
            set { this._stateProvince = value; }
        }
        
        private string _timezone;
        
        /// <summary>
        /// Optional.
        /// </summary>
        public string Timezone
        {
            get { return this._timezone; }
            set { this._timezone = value; }
        }
        
        /// <summary>
        /// Initializes a new instance of the Devices class.
        /// </summary>
        public Devices()
        {
            this.Impressions = new LazyList<Impressions>();
        }
        
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public virtual void DeserializeJson(JToken inputObject)
        {
            if (inputObject != null && inputObject.Type != JTokenType.Null)
            {
                JToken activeFromValue = inputObject["activeFrom"];
                if (activeFromValue != null && activeFromValue.Type != JTokenType.Null)
                {
                    this.ActiveFrom = ((DateTimeOffset)activeFromValue);
                }
                JToken activeToValue = inputObject["activeTo"];
                if (activeToValue != null && activeToValue.Type != JTokenType.Null)
                {
                    this.ActiveTo = ((DateTimeOffset)activeToValue);
                }
                JToken addressValue = inputObject["address"];
                if (addressValue != null && addressValue.Type != JTokenType.Null)
                {
                    this.Address = ((string)addressValue);
                }
                JToken address2Value = inputObject["address2"];
                if (address2Value != null && address2Value.Type != JTokenType.Null)
                {
                    this.Address2 = ((string)address2Value);
                }
                JToken address3Value = inputObject["address3"];
                if (address3Value != null && address3Value.Type != JTokenType.Null)
                {
                    this.Address3 = ((string)address3Value);
                }
                JToken assignedCampaignIdValue = inputObject["assignedCampaignId"];
                if (assignedCampaignIdValue != null && assignedCampaignIdValue.Type != JTokenType.Null)
                {
                    this.AssignedCampaignId = ((string)assignedCampaignIdValue);
                }
                JToken biasesForDevicesValue = inputObject["biasesForDevices"];
                if (biasesForDevicesValue != null && biasesForDevicesValue.Type != JTokenType.Null)
                {
                    BiasesForDevices biasesForDevices = new BiasesForDevices();
                    biasesForDevices.DeserializeJson(biasesForDevicesValue);
                    this.BiasesForDevices = biasesForDevices;
                }
                JToken cityValue = inputObject["city"];
                if (cityValue != null && cityValue.Type != JTokenType.Null)
                {
                    this.City = ((string)cityValue);
                }
                JToken currentCampaignValue = inputObject["currentCampaign"];
                if (currentCampaignValue != null && currentCampaignValue.Type != JTokenType.Null)
                {
                    Campaigns campaigns = new Campaigns();
                    campaigns.DeserializeJson(currentCampaignValue);
                    this.CurrentCampaign = campaigns;
                }
                JToken deviceIdValue = inputObject["deviceId"];
                if (deviceIdValue != null && deviceIdValue.Type != JTokenType.Null)
                {
                    this.DeviceId = ((string)deviceIdValue);
                }
                JToken deviceNameValue = inputObject["deviceName"];
                if (deviceNameValue != null && deviceNameValue.Type != JTokenType.Null)
                {
                    this.DeviceName = ((string)deviceNameValue);
                }
                JToken impressionsSequence = ((JToken)inputObject["impressions"]);
                if (impressionsSequence != null && impressionsSequence.Type != JTokenType.Null)
                {
                    foreach (JToken impressionsValue in ((JArray)impressionsSequence))
                    {
                        Impressions impressions = new Impressions();
                        impressions.DeserializeJson(impressionsValue);
                        this.Impressions.Add(impressions);
                    }
                }
                JToken postalCodeValue = inputObject["postalCode"];
                if (postalCodeValue != null && postalCodeValue.Type != JTokenType.Null)
                {
                    this.PostalCode = ((string)postalCodeValue);
                }
                JToken primaryKeyValue = inputObject["primaryKey"];
                if (primaryKeyValue != null && primaryKeyValue.Type != JTokenType.Null)
                {
                    this.PrimaryKey = ((string)primaryKeyValue);
                }
                JToken stateProvinceValue = inputObject["stateProvince"];
                if (stateProvinceValue != null && stateProvinceValue.Type != JTokenType.Null)
                {
                    this.StateProvince = ((string)stateProvinceValue);
                }
                JToken timezoneValue = inputObject["timezone"];
                if (timezoneValue != null && timezoneValue.Type != JTokenType.Null)
                {
                    this.Timezone = ((string)timezoneValue);
                }
            }
        }
    }
}
