// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Argonne.Services.ArgonneService.Models;
using Newtonsoft.Json.Linq;

namespace Argonne.Services.ArgonneService.Models
{
    public static partial class ImpressionDtoCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<ImpressionDto> DeserializeJson(JToken inputObject)
        {
            IList<ImpressionDto> deserializedObject = new List<ImpressionDto>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                ImpressionDto impressionDto = new ImpressionDto();
                impressionDto.DeserializeJson(iListValue);
                deserializedObject.Add(impressionDto);
            }
            return deserializedObject;
        }
    }
}
