// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using Argonne.Common.ArgonneService.Models;

namespace ArgonneAdDisplay.Model
{
    public partial class ImpressionResultset : ImpressionDto
    {
        public string Timestamp
        {
            get
            {
                //return this.DeviceTimestamp.Value.UtcDateTime;
                return this.DeviceTimestamp != null ? this.DeviceTimestamp.Value.UtcDateTime.ToString("yyyy-MM-ddTHH:mm:ss.fffZ") : string.Empty;
            }
        }

        public IList<ImpressionFace> Faces { get; set; }

        public string MessageType { get; set; }
    }
}
