// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Linq;
using Newtonsoft.Json.Linq;
using System.Collections.Generic;
using Argonne.Common.ArgonneService.Models;

namespace ArgonneAdDisplay.Model
{
    public partial class ImpressionResultset : ImpressionDto
    {
        public IList<ImpressionFace> Faces { get; set; }

        public string MessageType { get; set; }
    }
}
